grid_size = 4
mode = 0
randomness = 1
solution = [1, 10, 11, 12,
        2, 9, 8, 13,
        3, 4, 7, 14,
        5, 6, 15, 16]

[[fixed_positions]]
col = 0
row = 0
value = 1

[[fixed_positions]]
col = 3
row = 0
value = 12

[[fixed_positions]]
col = 1
row = 2
value = 4

[[fixed_positions]]
col = 3
row = 3
value = 16