fixed_values = [1, 4, 16, 7]
grid_size = 4
solution = [1, 2, 3, 4, 12, 13, 14, 5, 11, 16, 15, 6, 10, 9, 8, 7]

[[fixed_positions]]
col = 0
row = 0

[[fixed_positions]]
col = 3
row = 0

[[fixed_positions]]
col = 1
row = 2

[[fixed_positions]]
col = 3
row = 3
